#!/usr/bin/env ruby

hosts = ENV["KAMAL_HOSTS"].split(",")

hosts.each do |ip|
  destination = "root@#{ip}"
  puts "Creating a Docker network \"quicktube\" on #{destination}"
  `ssh #{destination} docker network create quicktube`
end

hosts.each do |ip|
  destination = "root@#{ip}"
  puts "Creating a Lets Encrypt acme.json with chmod 600 on #{destination}"
  `ssh #{destination} "mkdir -p /etc/letsencrypt && touch /etc/letsencrypt/acme.json && chmod 600 /etc/letsencrypt/acme.json"`
end
