<% require "dotenv"; Dotenv.load(".env") %>

service: quicktube

image: vladyio/quicktube

servers:
  web:
    hosts:
      - <%= ENV.fetch("HOST_IP") %>

builder:
  arch: amd64
  cache:
    type: registry
    options: mode=max,image-manifest=true,oci-mediatypes=true

proxy:
  ssl: true
  host: <%= ENV.fetch("KAMAL_PROXY_HOST") %>
  app_port: 3000

volumes:
  - "/rails/public/dl:/rails/public/dl"
  - "quicktube_storage:/rails/storage"
  - "/rails/config/cookies.txt:/rails/config/cookies.txt"

asset_path: /rails/public/assets

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    MAX_FILESIZE: 1G
    RETRIES: 5
    PATHS: public/dl
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: <%= ENV.fetch("SSH_USER", "root") %>
  port: <%= ENV.fetch("SSH_PORT", 22) %>

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

accessories:
  bgutil-provider:
    role: web
    image: brainicism/bgutil-ytdlp-pot-provider
    port: "127.0.0.1:4416:4416"



