name: Latest tag deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    status: success
  push:
    tags:
      - 'v*'

jobs:
  deploy-quicktube:
    name: Deploy Quicktube
    concurrency:
      group: production_environment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://quicktube.app
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/workflows/setup
        name: Setup
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Kamal Deploy
        uses: igor-alexandrov/kamal-deploy@v0.3.0
        with:
          registry-username: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          HOST_IP: ${{ vars.HOST_IP }}
          KAMAL_PROXY_HOST: ${{ vars.KAMAL_PROXY_HOST }}
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_PORT: ${{ vars.SSH_PORT }}
